name: Create Theme Package

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build Ghost Theme
      uses: foolscapcon/action-build-ghost-theme@v1.0.9
    - name: Upload Ghost Theme
      uses: actions/upload-artifact@v2
      with:
        name: lyra-cobalt-norfair00
        path: ghost-theme-lyra-cobalt-norfair00.zip